### ISSUE TITLE
Which firmware to use

### ISSUE THREAD

**Issue by xnuken** [Nitrokey/nitrokey-3-firmware#125]
There is no clear documentation on which firmware version to use for the Nitrokey 3A NFC or any of its variants. I recently purchased a 3A NFC and would like to know what is the correct firmware file to flash.

**Comment by robin-nitrokey** [comment]
`nitropy` automatically selects the latest stable firmware version.  So for regular usage, you can just run `nitropy nk3 update` to check whether your device is up to date.  We also plan to add a `list-updates` subcommand to `nitropy` so that you can easily check the available releases (https://github.com/Nitrokey/pynitrokey/issues/285).

You only need to manually select a firmware version if you want to use an alpha release.  The process for that is currently described [here](https://github.com/Nitrokey/opcard-rs/blob/main/USAGE.md).
