### ISSUE TITLE
GnuPG card list stalls while Nitrokey 3 is connected

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-3-firmware#22]
GnuPG card list stalls (for 30-60 seconds) while Nitrokey 3 is connected, blocking work with other user's smart cards. Further listing is cached, hence the delay is noticeable only the first time during given user session.

From the user POV, GnuPG operations should not be delayed.

OS: Linux Fedora 33
```
$ gpg2 --version
gpg (GnuPG) 2.2.25
libgcrypt 1.8.8
```

**Comment by robin-nitrokey** [comment]
This is caused by the missing abort handling in `usbd-ccid` (`src/pipe.rs`: [1](https://github.com/Nitrokey/nitrokey-3-firmware/blob/63ac04ae261e15fcbd565242722d3ffbf5b97a48/components/usbd-ccid/src/pipe.rs#L207), [2](https://github.com/Nitrokey/nitrokey-3-firmware/blob/63ac04ae261e15fcbd565242722d3ffbf5b97a48/components/usbd-ccid/src/pipe.rs#L523)).
