### ISSUE TITLE
Critical error: Failed to find firmware image for release v1.4.0-rc.2

### ISSUE THREAD

**Issue by proninyaroslav** [Nitrokey/nitrokey-3-firmware#257]
**pynitrokey**: 0.4.36

It seems the [release](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.4.0-rc.2) doesn't contain `firmware-nk3-v1.4.0-rc.2.zip` file.

**Comment by robin-nitrokey** [comment]
See the first sentence of the release notes:
> This release is currently in internal testing, signed binaries to be used with nitropy will be uploaded within the next days

It will probably be available this evening.

**Comment by robin-nitrokey** [comment]
It’s available now.  I know this is not ideal.  But on the one hand, we have to create the release so that the CI is triggered and builds the release binaries.  On the other hand, we don’t want to publish firmware images that have not been validated at least once on real hardware.  Therefore there is a delay of typically a few hours between the release is created on GitHub and the binaries are available.

**Comment by proninyaroslav** [comment]
@robin-nitrokey 
Thank you. It's just that I'm subscribed to the new releases in the repo and I can see the original release, but the release modifications are no longer being notified. Maybe it’s worth posting test builds in some other way, or creating a release again so that all members can see the changes (that it left the "test mode" and signed firmware is available).
