### ISSUE TITLE
NK3AN v.1.5.0 OpenPGP after NFC use

### ISSUE THREAD

**Issue by ghost** [Nitrokey/nitrokey-3-firmware#298]
.

**Comment by sosthene-nitrokey** [comment]
Hello, thank you for the report.

> Generated 3 4096 bit RSA keys via gpg on the NK

Did you generate them or import them? It is normally not possible to generate RSA key larger than 2048 bit on-device.

Did it happen only once or is it something that you are able to  consistently if when you enable UIF?

What were the last operations you performed before the PINs were reset to their default?

**Comment by jgoolde** [comment]
I followed instructions in https://docs.nitrokey.com/nitrokey3/linux/openpgp-keygen-on-device 
Once the key attributes are changed to 4096, it is exactly what NK3 shows.

The second time, I generated the keys outside of NK, following https://docs.nitrokey.com/nitrokey3/linux/openpgp-keygen-backup except for the key size where I chose 4096 instead of 2048

The issue with pin reset and card error happened both times.

> What were the last operations you performed before the PINs were reset to their default?
First time it was after I attempted to link NK3 with OpenKeychain via NFC - at that time I was not aware the NFC function does not work with OpenPGP.

Second time, I think it was `gpg --decrypt` - I was using that a lot (around 15 times).

**Comment by sosthene-nitrokey** [comment]
>  Once the key attributes are changed to 4096, it is exactly what NK3 shows.

I do not understand what you mean in this sentence. Could you please clarify?

Besides the PIN, was other data affected? For example the metadata you might have configured with `gpg --card-edit` or the Fido and secrets app?

**Comment by sosthene-nitrokey** [comment]
Hi,

It looks like the NFC usage, despite being unsupported can indeed cause the PINs to be reset due to an oversight in the implementation of the initialization step. This bug will be fixed in the next release of the firmware, see #301  and https://github.com/Nitrokey/opcard-rs/issues/165 for the relevant issues.

Meanwhile, we recommend you do not attempt to use OpenPGP over NFC.
