### ISSUE TITLE
Is it possible to run symmetric (aes or similar) block and stream cipher directly on the NK3?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nitrokey-3-firmware#497]
Is it possible to run AES or similar block and stream cipher directly on the NK3?

I.e., let us say I want to be able to perform symmetric encryption / decryption in a safe way. I would like to have the secret key checked onto the NK3 "checked in only, no way to extract it" like for the GPG private key, and then do the AES operations directly on the key (I guess this will, for speed reasons, only work for limited amounts of data, but fair enough).

Is this already supported / would this be doable / are there plans for making this possible? Not sure if there are standard APIs / methods, a la GPG-smartcard standard, to do this in a convenient way?

**Comment by sosthene-nitrokey** [comment]
Yes, this is possible through the GPG smartcard standard.

We respect [the specification](https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.4.1.pdf). See the `PSO:DECIPHER` and `PSO:ENCIPHER` commands. They will allow you to perform the encryption/decryption with AES 256 CBC on the NK3 with a key that cannot be extracted.

Be aware that the uses cases for this are limited since there is no authentication. Nonce reuse is also very dangerous.

**Comment by sosthene-nitrokey** [comment]
I am not aware of a simple resource just explaining how to communicate with the GPG application for this specific use case.

You probably want to start with learning about PC/SC and the library for that on your language of choice.

**Comment by robin-nitrokey** [comment]
I’m closing this issue as the question has been answered.  Feel free to re-open or create a new issue if the AES encryption and decryption does not work as expected.
